sudo: false
language: elixir
elixir:
  - 1.8
otp_release:
  - 21.0
cache:
  directories:
    - _build
    - deps
script:
  - mix test
  # - if [[ `elixir -v` = *"1.8"* ]]; then mix format --check-formatted; fi
  # - if [[ `elixir -v` = *"1.8"* ]]; then
  #     travis_wait 30 mix dialyzer --halt-exit-status --format term;
  #   fi

# matrix:
#   exclude:
#     - elixir: 1.5
#       otp_release: 21.0
#     - elixir: 1.8
#       otp_release: 19.3
